# Generated by Django 4.1.2 on 2022-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compagnie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
