# Generated by Django 4.1.2 on 2022-11-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compagnie', '0002_alter_compagnie_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnie',
            name='logo',
            field=models.ImageField(upload_to='airlaines'),
        ),
    ]
