# Generated by Django 4.1.2 on 2022-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField(null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('heure', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
