# Generated by Django 4.1.2 on 2022-11-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trajet', '0001_initial'),
        ('Vol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='trajet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Trajet.trajet'),
        ),
    ]
